{
 "title": "ArgoWorkflow Metrics",
 "tags": [ "prod" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "k8s_ns",
    "query": {
     "query": "label_values(argo_workflows_count{argocd_argoproj_io_instance=\"$argoinstance\"},kubernetes_namespace) "
    }
   },
   {
    "name": "argoinstance",
    "query": {
     "query": "label_values(argo_workflows_count{argocd_argoproj_io_instance=~\".*prod\"}, argocd_argoproj_io_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Currently", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://argoproj.github.io/static/6e944804f836bce176feffed44a8bf7e/68d6e/workflows.webp\"/>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "WF Pending",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Pending\", argocd_argoproj_io_instance=\"$argoinstance\"} "
    }
   ]
  },
  {
   "title": "WF Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Running\", argocd_argoproj_io_instance=\"$argoinstance\"}"
    }
   ]
  },
  {
   "title": "WF Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Error\", argocd_argoproj_io_instance=\"$argoinstance\"}"
    }
   ]
  },
  {
   "title": "WF Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Failed\", argocd_argoproj_io_instance=\"$argoinstance\"}"
    }
   ]
  },
  {
   "title": "WF Skipped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Skipped\", argocd_argoproj_io_instance=\"$argoinstance\"}"
    }
   ]
  },
  {
   "title": "WF Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argo_workflows_count{kubernetes_namespace=~\"$ns\",status=\"Succeeded\", argocd_argoproj_io_instance=\"$argoinstance\"}"
    }
   ]
  },
  {
   "title": "Number of Workflows currently accessible by the controller by status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Workflow Status  ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{status!~\"(Error|Failed)\",kubernetes_namespace=~\"$ns\", argocd_argoproj_io_instance=\"$argoinstance\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Workflow Errors Alerting ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_count{status=~\"(Error|Failed)\", argocd_argoproj_io_instance=\"$argoinstance\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{status}}"
    }
   ]
  },
  {
   "title": "Histogram of durations of operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Workflow operation duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(argo_workflows_operation_duration_seconds_bucket{kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])) by (le)) ",
     "legendFormat": "95th percentile"
    }
   ]
  },
  { "title": "Adds to the queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Workflow queue adds ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(argo_workflows_queue_adds_count{kubernetes_namespace=~\"$ns\", argocd_argoproj_io_instance=\"$argoinstance\"}[2m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Depth of the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "argo_workflows_queue_depth_count{kubernetes_namespace=~\"$ns\", argocd_argoproj_io_instance=\"$argoinstance\"}",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  {
   "title": "Time objects spend waiting in the queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s", "label": "avg" }
   ],
   "targets": [
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"cron_wf_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"cron_wf_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"pod_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"pod_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"wf_cron_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"wf_cron_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    },
    {
     "expr": "  rate(argo_workflows_queue_latency_sum{queue_name=\"workflow_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])\n/\n  rate(argo_workflows_queue_latency_count{queue_name=\"workflow_queue\",kubernetes_namespace=~\"^$ns$\", argocd_argoproj_io_instance=\"$argoinstance\"}[5m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{queue_name}}"
    }
   ]
  },
  { "title": "Total number of log messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Log messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "count/sec" }
   ],
   "targets": [
    {
     "expr": "rate(log_messages{kubernetes_namespace=~\"$ns\", argocd_argoproj_io_instance=\"$argoinstance\"}[2m])",
     "legendFormat": "{{app}} : {{kubernetes_namespace}} : {{level}}"
    }
   ]
  }
 ]
}