{
 "title": "Osiris egress",
 "tags": [ "prod" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "prod" },
   {
    "name": "egressinstance",
    "query": {
     "query": "label_values(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=~\".*egress.*$env\"},argocd_argoproj_io_instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_last_seen{kubernetes_azure_com_cluster=~\".*$env.*\"}, kubernetes_azure_com_cluster)"
    }
   },
   {
    "name": "currentPod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=\"osiris\", argocd_argoproj_io_instance=\"tooling-prometheus-prod\", phase=\"Running\", pod=~\".*egress.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Success percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\", \nstatus_code=~\"(2.*|HTTPStatus.CREATED|HTTPStatus.FOUND|HTTPStatus.NO_CONTENT|HTTPStatus.OK)\"}[2m]))\n/\nsum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}[2m]))"
    }
   ]
  },
  {
   "title": "4** percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\", \nstatus_code=~\"(4.*|)\"}[2m]))\n/\nsum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}[2m]))"
    }
   ]
  },
  {
   "title": "Internal server errors percent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\", \nstatus_code=~\"(5.*|HTTPStatus.BAD_REQUEST)\"}[2m]))\n/\nsum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}[2m]))"
    }
   ]
  },
  {
   "title": "Last seen status codes",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests / s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}[2m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.9, \n    sum by (le) (rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}[5m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.99, \n    sum by (le) (rate(starlette_request_duration_seconds_bucket{argocd_argoproj_io_instance=\"$egressinstance\", path!~\"/osiris-.*/\", path!~\"/osiris-.*/metrics\"}[5m])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", container!=\"\", namespace=\"osiris\", pod=\"$currentPod\", kubernetes_azure_com_cluster=\"$cluster\"}[2m]) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!=\"POD\", container!=\"\", namespace=\"osiris\", pod=\"$currentPod\", kubernetes_azure_com_cluster=\"$cluster\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}