{
 "title": "Pod lookup",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod_name" }
  ]
 },
 "panels": [
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=\"$pod_name\", container!=\"POD\", container!=\"\"}[2m]) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "memory workingset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"$pod_name\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"$pod_name\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}